CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    is_available BOOLEAN DEFAULT false
);

CREATE TABLE books_authors (
    book_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    CONSTRAINT pk_books_authors PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_books_authors_books FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT fk_books_authors_authors FOREIGN KEY (author_id) REFERENCES authors(id)
);